fsm:
  members:
    - alanfreer
    - alistairthomson
    - candicelauren
    - dylan-qton
    - electricstrm
    - Flacky
    - jamesrglover
    - johnline
    - jon-simmonds
    - karthikganta
    - liammorrensms
    - markqton
    - paulfeaviour
    - phlyk
    - owain-roberts
    - sms-simonyoung

  channel: '#dev'

  exclude_titles:
    - DO NOT MERGE

  use_labels: true

  exclude_labels:
    - wontfix

xperiment:
  members:
    - phlyk
    - jon-simmonds
    - sandratichanovaite

  channel: '#malteser-gate'

  quotes:
    - Let's get to the bottom of this!
    - Keep calm and malteeeeseee
    - "This is also just an experiment don't get worried. It's for the greater good :karthik:"
