fsm:
  members:
    - alanfreer
    - candicelauren
    - DanielTateSMS
    - dwilson-sms
    - dylan-qton
    - electricstrm
    - gordon-sms
    - jdunn-sms
    - johnline
    - jonathanyong81
    - jon-simmonds
    - jose-aviles
    - karthikganta
    - KasiaBM
    - liammorrensms
    - markqton
    - paulfeaviour
    - phlyk
    - owain-roberts
    - rich-blockley-sms
    - ryanbowensms
    - sms-simonyoung
    - StuBez

  channel: '#dev'

  exclude_titles:
    - DO NOT MERGE

  use_labels: true

  exclude_labels:
    - wontfix
