fsm:
  channel: '#dev'
  members:
    - alanfreer
    - akbarbaig
    - candicelauren
    - dylan-qton
    - Flacky
    - ilmaruk
    - isocra
    - jamesrglover
    - johnline
    - jon-simmonds
    - karthikganta
    - markqton
    - paulfeaviour
    - alistairthomson
    - owain-roberts
    - sms-simonyoung
  use_labels: true
  exclude_labels:
    - wip
